services:
  app:
    image: konradbaran/restaurant-backend-wpz:latest
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_PORT=5173
