version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: konradbaran/restaurant-backend-wpz
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./target:/app

    command: ["java", "-jar", "restaurantBackend.jar"]